services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      echo "=== BUILD STARTED ==="
      pwd
      ls -la
      
      # Install all dependencies using the root package.json script
      echo "=== INSTALLING ALL DEPENDENCIES ==="
      npm run install:all
      
      # Build frontend
      echo "=== BUILDING FRONTEND ==="
      cd frontend
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      
      # Install Angular CLI globally (needed for build)
      echo "=== INSTALLING ANGULAR CLI ==="
      npm install -g @angular/cli@16.2.0
      
      # Build frontend with production config
      echo "=== RUNNING FRONTEND BUILD ==="
      ng build --configuration production
      
      # Verify build
      echo "=== VERIFYING BUILD ==="
      if [ ! -d "dist/frontend" ]; then
        echo "ERROR: Frontend build directory not found"
        echo "Current directory contents:"
        ls -la
        echo "dist directory contents (if exists):"
        ls -la dist || echo "dist directory not found"
        exit 1
      fi
      
      echo "=== BUILD COMPLETED ==="
    startCommand: |
      # Start the backend server
      cd backend
      echo "=== STARTING BACKEND SERVER ==="
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..
      echo "Frontend dist contents:"
      ls -la ../frontend/dist/frontend || echo "Frontend dist not found"
      
      # Start the server in production mode
      NODE_ENV=production node server.js
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
          - package.json
          - package-lock.json
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 