services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      # Print initial directory structure
      echo "Initial directory structure:"
      pwd
      ls -la
      
      # Install Angular CLI globally
      echo "Installing Angular CLI..."
      npm install -g @angular/cli@16.2.0
      
      # Build frontend
      echo "Building frontend..."
      cd frontend
      echo "Frontend directory contents before build:"
      ls -la
      
      # Clean install frontend dependencies
      echo "Installing frontend dependencies..."
      rm -rf node_modules package-lock.json
      npm install
      
      # Build frontend with production config and show output
      echo "Running frontend build..."
      npm run build -- --configuration production --verbose
      
      # Verify frontend build
      echo "Verifying frontend build..."
      if [ ! -d "dist/frontend" ]; then
        echo "ERROR: Frontend build failed - dist/frontend not found"
        echo "Current directory contents:"
        ls -la
        echo "dist directory contents (if exists):"
        ls -la dist || true
        echo "node_modules contents:"
        ls -la node_modules || true
        exit 1
      fi
      
      # List frontend build contents
      echo "Frontend build contents:"
      ls -la dist/frontend
      
      # Verify index.html exists
      if [ ! -f "dist/frontend/index.html" ]; then
        echo "ERROR: index.html not found in dist/frontend"
        echo "dist/frontend contents:"
        ls -la dist/frontend
        exit 1
      fi
      
      # Install backend dependencies
      echo "Installing backend dependencies..."
      cd ../backend
      npm install
      
      # Final directory check
      echo "Final directory structure:"
      cd ..
      echo "Root directory contents:"
      ls -la
      echo "Frontend directory contents:"
      ls -la frontend
      echo "Frontend dist contents:"
      ls -la frontend/dist/frontend
      
      # Verify the build one last time
      if [ ! -f "frontend/dist/frontend/index.html" ]; then
        echo "ERROR: Final verification failed - index.html not found"
        echo "Directory structure:"
        find . -type d -maxdepth 3
        exit 1
      fi
    startCommand: |
      cd backend
      echo "Starting server from:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..
      echo "Frontend directory contents:"
      ls -la ../frontend
      echo "Frontend dist contents:"
      ls -la ../frontend/dist/frontend || echo "Frontend dist not found"
      npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 