services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      #!/bin/bash
      set -e  # Exit on error
      
      echo "=== BUILD STARTED ==="
      echo "Current directory: $(pwd)"
      
      # Install Node.js 18.x if not already installed
      echo "=== SETTING UP NODE.JS ==="
      if ! command -v nvm &> /dev/null; then
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      fi
      nvm install 18
      nvm use 18
      
      # Install root dependencies
      echo "=== INSTALLING ROOT DEPENDENCIES ==="
      npm cache clean --force
      npm install --legacy-peer-deps
      
      # Install frontend dependencies (just Express)
      echo "=== INSTALLING FRONTEND EXPRESS SERVER ==="
      cd frontend
      echo "Frontend directory: $(pwd)"
      npm install express --save
      
      # Create frontend directory structure
      echo "=== SETTING UP FRONTEND STATIC FILES ==="
      mkdir -p dist/frontend
      
      # Run backend installation
      echo "=== INSTALLING BACKEND DEPENDENCIES ==="
      cd ../backend
      npm install --legacy-peer-deps
      
      echo "=== BUILD COMPLETED ==="
    startCommand: |
      echo "=== STARTING SERVICES ==="
      npm run start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
          - package.json
          - package-lock.json
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 