services:
  - type: web
    name: ipt-final-api
    env: node
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /api-docs
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: FRONTEND_URL
        value: https://ipt-final.onrender.com
      - key: BACKEND_URL
        value: https://ipt-final-api.onrender.com 