services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      # Print initial directory structure
      echo "Initial directory structure:"
      pwd
      ls -la
      
      # Install Angular CLI globally
      echo "Installing Angular CLI..."
      npm install -g @angular/cli
      
      # Build frontend
      echo "Building frontend..."
      cd frontend
      npm install
      npm run build -- --configuration production
      
      # Verify frontend build
      echo "Verifying frontend build..."
      if [ ! -d "dist/frontend" ]; then
        echo "ERROR: Frontend build failed - dist/frontend not found"
        ls -la dist
        exit 1
      fi
      
      # List frontend build contents
      echo "Frontend build contents:"
      ls -la dist/frontend
      
      # Go back to root and install backend dependencies
      cd ../backend
      echo "Installing backend dependencies..."
      npm install
      
      # Final directory check
      echo "Final directory structure:"
      cd ..
      pwd
      ls -la
      echo "Frontend dist contents:"
      ls -la frontend/dist/frontend
    startCommand: |
      cd backend
      echo "Starting server from:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..
      npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 