services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      # Install dependencies for both frontend and backend
      npm install -g @angular/cli
      # Build frontend
      cd frontend && npm install && npm run build -- --configuration production
      # Verify frontend build
      if [ ! -d "dist/frontend" ]; then
        echo "Frontend build failed - dist/frontend directory not found"
        exit 1
      fi
      # Create backend/frontend-dist if it doesn't exist
      cd .. && mkdir -p backend/frontend-dist
      # Copy frontend build files with verbose output
      echo "Copying frontend build files..."
      cp -rv frontend/dist/frontend/* backend/frontend-dist/
      # Verify the copy
      if [ ! -f "backend/frontend-dist/index.html" ]; then
        echo "Failed to copy frontend files - index.html not found"
        exit 1
      fi
      echo "Frontend files copied successfully"
      # Install backend dependencies
      cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 