services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      #!/bin/bash
      set -e  # Exit on error
      
      echo "=== BUILD STARTED ==="
      echo "Current directory: $(pwd)"
      
      # Install Node.js 18.x if not already installed
      echo "=== SETTING UP NODE.JS ==="
      if ! command -v nvm &> /dev/null; then
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      fi
      nvm install 18
      nvm use 18
      
      # Install root dependencies
      echo "=== INSTALLING ROOT DEPENDENCIES ==="
      npm cache clean --force
      npm install --legacy-peer-deps
      
      # Build frontend
      echo "=== BUILDING FRONTEND ==="
      cd frontend
      echo "Frontend directory: $(pwd)"
      
      # Clean and reinstall frontend dependencies
      echo "=== CLEANING AND REINSTALLING FRONTEND ==="
      npm run reinstall
      
      # Build with increased memory limit
      echo "=== RUNNING ANGULAR BUILD ==="
      NODE_OPTIONS="--max_old_space_size=4096" ./node_modules/.bin/ng build --configuration production
      
      # Verify build output
      echo "=== VERIFYING BUILD ==="
      if [ ! -d "dist/frontend" ]; then
        echo "ERROR: Frontend build directory not found"
        echo "Current directory contents:"
        ls -la
        echo "dist directory contents (if exists):"
        ls -la dist || true
        exit 1
      fi
      
      echo "=== BUILD COMPLETED ==="
    startCommand: |
      cd backend
      echo "=== STARTING SERVER ==="
      NODE_ENV=production npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
          - package.json
          - package-lock.json
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 