services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      set -ex  # Exit on any error and print commands
      
      # Print initial directory structure
      echo "=== INITIAL DIRECTORY STRUCTURE ==="
      pwd
      ls -la
      
      # Check if root package.json exists
      echo "=== CHECKING ROOT PACKAGE.JSON ==="
      if [ ! -f "package.json" ]; then
        echo "ERROR: Root package.json not found. Please ensure it exists in the repository."
        exit 1
      else
        echo "Root package.json found"
        cat package.json
      fi
      
      # Install root dependencies
      echo "=== INSTALLING ROOT DEPENDENCIES ==="
      npm install --legacy-peer-deps
      
      # Install Angular CLI globally
      echo "=== INSTALLING ANGULAR CLI ==="
      npm run install:angular
      
      # Verify Angular CLI installation
      echo "=== VERIFYING ANGULAR CLI ==="
      ng version
      
      # Run the build script which will build both frontend and backend
      echo "=== RUNNING BUILD SCRIPT ==="
      npm run build
      
      # Verify the build
      echo "=== VERIFYING BUILD ==="
      if [ ! -d "frontend/dist/frontend" ]; then
        echo "ERROR: Frontend build not found"
        echo "Directory contents:"
        ls -la
        echo "Frontend directory contents:"
        ls -la frontend
        exit 1
      fi
      
      echo "Frontend build found:"
      ls -la frontend/dist/frontend
      
      echo "=== BUILD COMPLETED SUCCESSFULLY ==="
    startCommand: |
      echo "=== STARTING SERVER ==="
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      
      # Verify frontend build exists
      echo "=== VERIFYING FRONTEND BUILD ==="
      if [ ! -d "frontend/dist/frontend" ]; then
        echo "ERROR: Frontend build not found"
        echo "Current directory contents:"
        ls -la
        echo "Frontend directory contents:"
        ls -la frontend
        exit 1
      fi
      
      echo "Frontend build found:"
      ls -la frontend/dist/frontend
      
      # Start the server
      echo "=== STARTING APPLICATION ==="
      cd backend
      NODE_ENV=production npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 