services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      echo "=== BUILD STARTED ==="
      pwd
      ls -la
      
      # Install all dependencies using the root package.json script
      echo "=== INSTALLING ALL DEPENDENCIES ==="
      npm run install:all
      
      # Build frontend
      echo "=== BUILDING FRONTEND ==="
      cd frontend
      npm run build -- --configuration production
      
      # Verify build
      echo "=== VERIFYING BUILD ==="
      if [ ! -d "dist/frontend" ]; then
        echo "ERROR: Frontend build directory not found"
        exit 1
      fi
      
      echo "=== BUILD COMPLETED ==="
    startCommand: |
      cd backend
      echo "=== STARTING SERVER ==="
      NODE_ENV=production npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
          - package.json
          - package-lock.json
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 