services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      set -ex  # Exit on any error and print commands
      
      # Print initial directory structure
      echo "=== INITIAL DIRECTORY STRUCTURE ==="
      pwd
      ls -la
      
      # Create root package.json if it doesn't exist
      echo "=== CREATING ROOT PACKAGE.JSON ==="
      if [ ! -f "package.json" ]; then
        echo "Creating root package.json..."
        cat > package.json << EOF
{
  "name": "ipt-final",
  "version": "1.0.0",
  "description": "IPT Final Project with Angular frontend and Node.js backend",
  "scripts": {
    "start": "node backend/server.js",
    "server": "cd backend && npm run dev",
    "client": "cd frontend && npm start",
    "dev": "concurrently \"npm run server\" \"npm run client\""
  },
  "dependencies": {
    "concurrently": "^8.2.0"
  }
}
EOF
        echo "Root package.json created"
      else
        echo "Root package.json already exists"
      fi
      
      # Install root dependencies including concurrently
      echo "=== INSTALLING ROOT DEPENDENCIES ==="
      npm install --verbose
      
      # Install Angular CLI globally
      echo "=== INSTALLING ANGULAR CLI ==="
      npm install -g @angular/cli@16.2.0
      ng version
      
      # Build frontend
      echo "=== STARTING FRONTEND BUILD ==="
      cd frontend
      echo "Current directory:"
      pwd
      echo "Frontend directory contents:"
      ls -la
      
      # Clean install frontend dependencies
      echo "=== INSTALLING FRONTEND DEPENDENCIES ==="
      echo "Removing existing node_modules and package-lock.json..."
      rm -rf node_modules package-lock.json
      echo "Running npm install..."
      npm install --verbose
      
      # Build frontend with production config
      echo "=== BUILDING FRONTEND ==="
      echo "Running ng build..."
      NODE_OPTIONS="--max_old_space_size=4096" ng build --configuration production --verbose
      
      # Verify build output
      echo "=== VERIFYING BUILD OUTPUT ==="
      echo "Checking dist directory..."
      if [ ! -d "dist" ]; then
        echo "ERROR: dist directory not created"
        echo "Current directory contents:"
        ls -la
        echo "npm list output:"
        npm list
        exit 1
      fi
      
      echo "Checking dist/frontend directory..."
      if [ ! -d "dist/frontend" ]; then
        echo "ERROR: dist/frontend directory not created"
        echo "dist directory contents:"
        ls -la dist
        echo "npm list output:"
        npm list
        exit 1
      fi
      
      echo "Checking for index.html..."
      if [ ! -f "dist/frontend/index.html" ]; then
        echo "ERROR: index.html not found in dist/frontend"
        echo "dist/frontend contents:"
        ls -la dist/frontend
        echo "npm list output:"
        npm list
        exit 1
      fi
      
      echo "Frontend build contents:"
      ls -la dist/frontend
      
      # Install backend dependencies
      echo "=== INSTALLING BACKEND DEPENDENCIES ==="
      cd ../backend
      echo "Current directory:"
      pwd
      echo "Installing backend dependencies..."
      npm install --verbose
      
      # Final verification
      echo "=== FINAL VERIFICATION ==="
      cd ..
      echo "Root directory contents:"
      ls -la
      echo "Frontend directory contents:"
      ls -la frontend
      echo "Frontend dist contents:"
      ls -la frontend/dist/frontend
      
      # One last check
      if [ ! -f "frontend/dist/frontend/index.html" ]; then
        echo "ERROR: Final verification failed - index.html not found"
        echo "Directory structure:"
        find . -type d -maxdepth 3
        echo "npm list output from frontend:"
        cd frontend && npm list
        exit 1
      fi
      
      echo "=== BUILD COMPLETED SUCCESSFULLY ==="
    startCommand: |
      cd backend
      echo "=== STARTING SERVER ==="
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..
      echo "Frontend directory contents:"
      ls -la ../frontend
      echo "Frontend dist contents:"
      ls -la ../frontend/dist/frontend || echo "Frontend dist not found"
      echo "=== STARTING NODE SERVER ==="
      NODE_ENV=production npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 