services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      # Install dependencies for both frontend and backend
      npm install -g @angular/cli
      cd frontend && npm install && npm run build -- --configuration production
      cd ../backend && npm install
      # Move frontend build to the correct location
      mkdir -p backend/frontend-dist
      cp -r frontend/dist/frontend/* backend/frontend-dist/
    startCommand: cd backend && npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 