services:
  # Backend API Service
  - type: web
    name: ipt-final-api
    env: node
    # Only build backend dependencies
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    # Note: Frontend should be deployed separately to a static hosting service
    # or as a separate Render service
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: FRONTEND_URL
        value: https://ipt-final.onrender.com
      - key: BACKEND_URL
        value: https://ipt-final-api.onrender.com 