services:
  - type: web
    name: ipt-final-api
    env: node
    rootDir: .
    buildCommand: |
      # Print current directory for debugging
      pwd
      ls -la
      
      # Install dependencies for both frontend and backend
      npm install -g @angular/cli
      
      # Build frontend
      echo "Building frontend..."
      cd frontend
      npm install
      npm run build -- --configuration production
      
      # Print frontend build directory contents
      echo "Frontend build directory contents:"
      ls -la dist/frontend
      
      # Go back to root and create the target directory
      cd ..
      echo "Creating frontend-dist directory..."
      mkdir -p backend/frontend-dist
      
      # Copy frontend build files
      echo "Copying frontend files..."
      cp -rv frontend/dist/frontend/* backend/frontend-dist/
      
      # Verify the copy
      echo "Verifying copied files..."
      ls -la backend/frontend-dist
      
      if [ ! -f "backend/frontend-dist/index.html" ]; then
        echo "ERROR: index.html not found in backend/frontend-dist"
        echo "Current directory structure:"
        pwd
        ls -la
        echo "Frontend dist contents:"
        ls -la frontend/dist/frontend
        echo "Backend frontend-dist contents:"
        ls -la backend/frontend-dist
        exit 1
      fi
      
      # Install backend dependencies
      echo "Installing backend dependencies..."
      cd backend
      npm install
      
      # Final verification
      echo "Final directory structure:"
      pwd
      ls -la
      ls -la frontend-dist
    startCommand: |
      cd backend
      echo "Starting server from directory:"
      pwd
      ls -la
      ls -la frontend-dist
      npm start
    healthCheckPath: /api-docs
    autoDeploy: true
    buildFilter:
      paths:
        include:
          - backend/**
          - frontend/**
        ignore:
          - **/node_modules/**
          - **/.git/**
          - **/.env
          - **/.env.*
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_jumaoas
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_jumaoas
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: PRODUCTION_FRONTEND_URL
        value: https://ipt-final-jzfb.onrender.com 